### ISSUE TITLE
Access token error

### ISSUE THREAD

**Issue by f-idelio** [elnkosc/stromer_api#2] opened 2023-06-27 18:14 UTC
There is an issue with getting the access token. 

I use IDLE shell and run the following commands to start it:
```
from stromer_api import StromerBike
mybike = StromerBike("myemail-at-domain.com", "my-password", "the famous client ID")
```

The error messages:

> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/stromer_api/portal.py", line 50, in __init__
>     self.__access_token = res.json()["access_token"]
> KeyError: 'access_token'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<pyshell#2>", line 1, in <module>
>     mybike = StromerBike("myemail-at-domain.com", "my-password", "the famous client ID")
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/stromer_api/__init__.py", line 22, in __init__
>     self.__portal = Portal(username, password, client_id)
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/stromer_api/portal.py", line 54, in __init__
>     raise Exception("Authentication failed")
> Exception: Authentication failed

The first step of getting the code with username and password works and a code is returned. The step of getting the access token fails.

Any solution to this? Could it be related to the stormer servers?

**Comment by elnkosc** [comment] 2023-07-15 18:43
Solution merged into main branch. Seemed to be caused by change in the stromer portal.

**Closed as completed by elnkosc** 2023-07-15 18:43 UTC
